import test from "node:test";
import assert from "node:assert/strict";

import { parseARRS, renderARRS } from "../src/arrs.js";

test("renders deterministic Anywhere rule sets", () => {
  const text = renderARRS(
    { name: "🤖 AI 专用", routing: 0 },
    [
      { type: 2, value: "openai.com" },
      { type: 0, value: "1.2.3.0/24" },
    ],
    ["OpenAI", "Claude"],
    "0.1.0",
  );
  assert.match(text, /^# Generated by anywhere-profile 0\.1\.0/m);
  assert.doesNotMatch(text, /2026-|T\d\d:/);
  assert.deepEqual(parseARRS(text), {
    name: "🤖 AI 专用",
    routing: 0,
    rules: [
      { type: 0, value: "1.2.3.0/24" },
      { type: 2, value: "openai.com" },
    ],
  });
});

test("rejects malformed Anywhere files", () => {
  assert.throws(() => parseARRS("name = one\nname = two\n2, example.com\n"), /Duplicate/);
  assert.throws(() => parseARRS("name = one\nrouting = 9\n2, example.com\n"), /routing/);
  assert.throws(() => parseARRS("name = one\nrouting = 1\n4, example.com\n"), /type/);
  assert.throws(() => parseARRS("name = one\nrouting = 1\n2,\n"), /rule/);
});

