import { parseCIDR } from "./cidr.js";

export const ANYWHERE_MAX_RULES = 100_000;

function compareRules(left, right) {
  if (left.type !== right.type) return left.type - right.type;
  return left.value.localeCompare(right.value, "en");
}

export function renderARRS(group, rules, sourceIds, generatorVersion) {
  if (!group?.name || ![0, 1, 2].includes(group.routing)) {
    throw new Error("Invalid ARR group");
  }
  if (!Array.isArray(rules) || rules.length === 0) {
    throw new Error(`Cannot render empty ARR group: ${group.name}`);
  }
  if (rules.length > ANYWHERE_MAX_RULES) {
    throw new Error(`ARR rule count exceeds Anywhere limit: ${rules.length}`);
  }
  if (!Array.isArray(sourceIds) || !sourceIds.length) {
    throw new Error(`Missing ARR sources: ${group.name}`);
  }
  const sorted = rules
    .map(({ type, value }) => ({ type, value }))
    .toSorted(compareRules);
  const lines = [
    `# Generated by anywhere-profile ${generatorVersion}`,
    `# Sources: ${sourceIds.join(", ")}`,
    "# Do not edit this generated file by hand.",
    `name = ${group.name}`,
    `routing = ${group.routing}`,
    "",
    ...sorted.map((rule) => `${rule.type}, ${rule.value}`),
    "",
  ];
  return lines.join("\n");
}

export function parseARRS(text) {
  if (typeof text !== "string") throw new Error("Invalid ARR text");
  let name;
  let routing;
  const rules = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#") || line.startsWith("//")) continue;
    const headerMatch = line.match(/^([A-Za-z][A-Za-z0-9_-]*)\s*=\s*(.*)$/);
    if (headerMatch) {
      const key = headerMatch[1].toLowerCase();
      const value = headerMatch[2].trim();
      if (key === "name") {
        if (name !== undefined) throw new Error("Duplicate ARR name");
        if (!value) throw new Error("Invalid ARR name");
        name = value;
      } else if (key === "routing") {
        if (routing !== undefined) throw new Error("Duplicate ARR routing");
        routing = Number(value);
        if (![0, 1, 2].includes(routing)) throw new Error("Invalid ARR routing");
      } else {
        throw new Error(`Unknown ARR header: ${key}`);
      }
      continue;
    }

    const match = line.match(/^(\d+)\s*,\s*(\S.*)$/);
    if (!match) throw new Error(`Invalid ARR rule: ${line}`);
    const type = Number(match[1]);
    if (![0, 1, 2, 3].includes(type)) throw new Error(`Invalid ARR rule type: ${line}`);
    let value = match[2].trim();
    if (!value || value.includes(",")) throw new Error(`Invalid ARR rule: ${line}`);
    if (type === 0 || type === 1) {
      const cidr = parseCIDR(value);
      if ((type === 0 && cidr.version !== 4) || (type === 1 && cidr.version !== 6)) {
        throw new Error(`Invalid ARR IP type: ${line}`);
      }
      value = cidr.canonical;
    }
    rules.push({ type, value });
  }
  if (!name) throw new Error("Missing ARR name");
  if (routing === undefined) routing = 0;
  return { name, routing, rules: rules.toSorted(compareRules) };
}
